### ISSUE TITLE
Qustion regarding perfomance

### ISSUE THREAD

**Issue by Ox3rror** [vladkens/macmon#3]
Hello,

First of all sorry for this dumb questions, I have Mac air m1 8gb, if i install this , does it affect perfomance?

Thanks.

**Comment by vladkens** [comment]
Hi, @Ox3rror 

Hi. The application consumes 5 MB of memory and causes a small CPU load of 1-1.5% (because it collects metrics once per second).

You can change the refresh interval with the -i parameter: `macmon -i 2000` (2 sec interval, 1 sec by default).

In general, this is probably one of the lowest resorces consumption in programs of that sort.

The only limitation I would highlight is that if you are running on battery, it is better not to keep the program on all the time, because it will discharge the battery a bit faster.
