### ISSUE TITLE
showing high E-CPU and probably P-CPU too

### ISSUE THREAD

**Issue by GregGorman** [vladkens/macmon#9]
macmon is continuously showing 40%+ E-CPU while glances and activity mon are showing < 5%

<img width="1087" alt="m3max_sequoia_15_0_1" src="https://github.com/user-attachments/assets/b07fafc4-0839-43d6-b13e-a72c8a931ad1">
<img width="1087" alt="m3max_sequoia_15_0_1_activity_mon" src="https://github.com/user-attachments/assets/a6d6564f-9015-4b17-be35-3b3aff42c391">

**Comment by vladkens** [comment]
Hi @GregGorman. As I remember, the M3 Max may have something called DOWN state for cores, so I think the numbers are not correct because of that.

Can you help me with debugging? I added [extra log](https://github.com/vladkens/macmon/commit/e27382283c5b3fbff63f9d51c686cd11cbc94d23) in v0.3.2.

Could you please update macmon with:

```sh
brew update && brew upgrade macmon
```

and run:

```sh
macmon debug
```

I need first two blocks AppleARMIODevice and IOReport

**Comment by GregGorman** [comment]
[macmon_debug.txt](https://github.com/user-attachments/files/17480901/macmon_debug.txt)

Here you go

**Comment by GregGorman** [comment]
i do like the gauge view, makes it easy to focus on the now vs the sparkline history view.

**Comment by vladkens** [comment]
@GregGorman thanks for the debug log, it helped a lot.

I've released a fix in [v0.3.3](https://github.com/vladkens/macmon/releases/tag/v0.3.3). Please try it:

```sh
brew update && brew upgrade macmon
```

**Comment by GregGorman** [comment]
Works great now! Yeah, I see how you needed that log file.

<img width="1078" alt="Screenshot 2024-10-27 at 3 00 56 PM" src="https://github.com/user-attachments/assets/1cd777ba-970c-4acb-9ea5-38e501f95abf">

**Comment by vladkens** [comment]
@GregGorman Glad it's working well now. Thanks for the logs, that helped.

Can I close the issue?
